include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test

variables:
  BUNDLE: 'manette-test-git.flatpak'

check-api-visibility:
  stage: test
  script:
    - tools/check-api-visibility.sh

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'demos/manette-test/org.gnome.Manette.Test.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'libmanette'
    APP_ID: 'org.gnome.Manette.Test'
    GIT_SUBMODULE_STRATEGY: recursive

fedora:
  image: fedora:32
  stage: test
  before_script:
    - dnf install -y gcc glib2-devel gobject-introspection-devel libevdev-devel libgudev-devel meson vala
  script:
    - meson _build
    - ninja -C _build
    - ninja -C _build test
