include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: deploy
      dist-job-name: "build-flatpak"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

stages:
  - build
  - deploy

variables:
  FLATPAK_BUILD_DIR: build
  APP_ID: 'org.gnome.Manette1.Demo'
  BUNDLE: 'org.gnome.Manette1.Demo.flatpak'
  RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
  MANIFEST_PATH: 'demo/org.gnome.Manette1.Demo.json'
  FLATPAK_MODULE: 'libmanette'
  TARBALL_ARTIFACT_PATH: ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

lint:
  stage: build
  script:
    - tools/check-api-visibility.sh

build-flatpak:
  extends: '.flatpak@x86_64'
  stage: build
  before_script: []
  needs: []

gudev:
  image: fedora:42
  stage: build
  before_script:
    - dnf install -y gcc glib2-devel gobject-introspection-devel hidapi-devel libevdev-devel libgudev-devel meson vala
  script:
    - meson setup _build -Ddemos=false
    - ninja -C _build
    - ninja -C _build test

doc:
  image: fedora:42
  stage: build
  before_script:
    - dnf install -y gcc glib2-devel gobject-introspection-devel hidapi-devel libevdev-devel libgudev-devel meson gi-docgen
  variables:
    MESON_ARGS: >-
      -Ddoc=true
      -Ddemos=false
      -Dbuild-tests=false
      -Dvapi=false
  script:
    - meson setup --fatal-meson-warnings --prefix=/app ${MESON_ARGS} _build
    - ninja -C _build
    - meson test -C _build --suite manette-1:doc
    - mv _build/doc/manette-1 _doc/
  artifacts:
    expose_as: 'Browse documentation'
    paths:
      - _doc/index.html
      - _doc

refresh-doc:
  image: fedora:42
  stage: deploy
  needs: ['doc']
  only:
    refs:
    - 'main'
  script:
    - "curl -X POST -F token=${PAGES_TRIGGER_TOKEN} -F ref=pages https://gitlab.gnome.org/api/v4/projects/148/trigger/pipeline"
