include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - pre
  - build

variables:
  BUNDLE: 'manette-test-git.flatpak'
  FLATPAK_BUILD_DIR: app
  SHARED_MESON_ARGS: >-
    --buildtype=release
    -Ddemos=false

lint:
  stage: pre
  script:
    - tools/check-api-visibility.sh

dependencies:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: pre
  tags:
    - flatpak
  variables:
    MANIFEST_PATH: demos/manette-test/org.gnome.Manette.Test.json
    FLATPAK_MODULE: libmanette
  script:
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
  artifacts:
    paths:
      - ${FLATPAK_BUILD_DIR}

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'demos/manette-test/org.gnome.Manette.Test.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'libmanette'
    APP_ID: 'org.gnome.Manette.Test'
    GIT_SUBMODULE_STRATEGY: recursive

unit-tests:
  image: fedora:32
  stage: build
  before_script:
    - dnf install -y gcc glib2-devel gobject-introspection-devel libevdev-devel libgudev-devel meson vala
  script:
    - meson _build
    - ninja -C _build
    - ninja -C _build test
